sudo: required

install:
  - sudo apt-get install libconfig++-dev libboost-all-dev python3-pip
  - source travis-scripts/install-cuda-trusty.sh
  - source travis-scripts/install-exprtk.sh
  - source travis-scripts/install-eigen.sh
  - touch githash.h
  - mkdir -p output/roberts
  - sudo pip3 install filelock

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make -f travis.make SYSTEM=roberts roberts-unit-tests
  - ./roberts-unit-tests --log_level=all
  - make -f travis.make SYSTEM=roberts
  - ./regression-tests -s roberts --disable-cuda

