sudo: required

install:
  - sudo pip install filelock
  - sudo apt-get install libconfig++-dev libboost-all-dev
  - source travis-scripts/install-cuda-trusty.sh
  - source travis-scripts/install-exprtk.sh
  - source travis-scripts/install-eigen.sh
  - touch githash.h

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make -f travis.make SYSTEM=roberts unit-tests
  - make -f travis.make SYSTEM=roberts regression-tests
    #  - make -f travis.make SYSTEM=myers
    #  - make -f travis.make SYSTEM=roberts unit-tests
#  - make -f travis.make SYSTEM=myers unit-tests

