sudo: required

install:
  - sudo apt-get install libboost-all-dev libconfig-dev
  - source travis-scripts/install-cuda-trusty.sh
  - source travis-scripts/install-exprtk.sh
  - source travis-scripts/install-eigen.sh
  - touch githash.h

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

# Build steps
script:
  - make -f travis.make SYSTEM=roberts
  - make -f travis.make SYSTEM=myers

